In [2]:
import numpy as np
x =  np.arange(2, 11).reshape(3,3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [3]:
ID_mat=np.identity(3)
print(ID_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
#1- identity matrix
Res=np.dot(ID_mat,x)
print("The dot product of two matrices:\n", Res)

The dot product of two matrices:
 [[ 2.  3.  4.]
 [ 5.  6.  7.]
 [ 8.  9. 10.]]


In [5]:
#2- zeros matrix
Z =np.zeros((3,3))
print(Z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
Res2=np.dot(x,Z)
print("The dot product of two matrices:\n", Res2)

The dot product of two matrices:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
#3- matrix's transpose
M1 = np.array([[1, 2, 3], [4, 5, 6],[7, 8, 9]])

print(f'Original Matrix:\n{M1}')

marix_transpose = M1.transpose()

print(f'Transposed matrix:\n{marix_transpose}')

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
#Another way for transposing
x =  np.arange(3, 12).reshape(3,3)
print(x)
marix_trnsps = x.transpose()

print(f'Transposed matrix:\n{marix_trnsps}')

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Transposed matrix:
[[ 3  6  9]
 [ 4  7 10]
 [ 5  8 11]]


In [9]:
#Another way for transposing
N = 3
 
def transpose(A,B):
 
 for i in range(N):
  for j in range(N):
   B[i][j] = A[j][i]
 
# driver code
A = [ [1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 3, 6, 7],
 ]
 
 
B = A[:][:] # To store results at
 
transpose(A, B) # invoking function
# print("Original matrix is:\n",A) 
print("Transposed matrix is:")
for i in range(N):
 for j in range(N):
  print(B[i][j], " ", end='')
 print()

Transposed matrix is:
1  2  3  
2  3  3  
3  3  6  
